# Generated by Django 3.1.5 on 2023-04-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdhocRequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_JD_1', models.CharField(blank=True, help_text='Target Job Description', max_length=5000, null=True)),
                ('target_JD_2', models.CharField(blank=True, help_text='Target Job Description', max_length=5000, null=True)),
                ('ques_details', models.CharField(blank=True, max_length=3000, null=True)),
                ('why_needed', models.CharField(choices=[('cd01', 'Didnot Find this serv in exp180'), ('cd02', 'I donotk now where to search'), ('cd03', 'it was time consuming to search for this')], default='no', max_length=100)),
                ('f_name', models.CharField(blank=True, max_length=100, null=True)),
                ('l_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('resume', models.FileField(default='null', upload_to='adhoc_resumes/%Y/%m/%d')),
            ],
            options={
                'verbose_name_plural': 'Adhoc Requests',
            },
        ),
    ]
