# Generated by Django 3.2.16 on 2023-05-01 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import resumeweb.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerListGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=300)),
                ('reguser', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(default='00000000000', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('updated', models.DateTimeField(auto_now=True, help_text='timestamp of last update')),
            ],
            options={
                'verbose_name': 'Buyer Email List',
                'verbose_name_plural': 'Buyer Email List',
            },
        ),
        migrations.CreateModel(
            name='mcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_uniqid', models.CharField(max_length=100)),
                ('title', models.CharField(default='mcart title value Not Set', max_length=500)),
                ('sku', models.CharField(max_length=6)),
                ('removed', models.BooleanField(default=False)),
                ('purchased', models.BooleanField(default=False)),
                ('resume_required', models.BooleanField(default=False)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('error', 'Error')], default='pending', max_length=20)),
                ('tracking_id', models.CharField(blank=True, max_length=50, null=True)),
                ('model_name', models.CharField(max_length=50)),
                ('item_id', models.IntegerField(default=0)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, help_text='this is the sale price at the time.', max_digits=1000)),
                ('coupon_subtract', models.DecimalField(decimal_places=2, default=0, help_text='this is the amount subtracted from base price due to coupons.', max_digits=1000)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, help_text='this is the final price after discounts.', max_digits=1000)),
                ('tax_price', models.DecimalField(decimal_places=2, default=0, help_text='this is the tax that will be calculated on this mcart item.', max_digits=1000)),
                ('quantity', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('updated', models.DateTimeField(auto_now=True, help_text='timestamp of last update')),
            ],
        ),
        migrations.CreateModel(
            name='mcompleted_purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypaltransaction_id', models.CharField(default='', max_length=100)),
                ('payer_id', models.CharField(default='', max_length=100)),
                ('capture_id', models.CharField(default='', max_length=100)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('email_address', models.CharField(default='', max_length=1000)),
                ('guest_login_email_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('updated', models.DateTimeField(auto_now=True, help_text='timestamp of last update')),
            ],
        ),
        migrations.CreateModel(
            name='mcompleted_refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypalrefund_id', models.CharField(max_length=100)),
                ('amount_currencycode', models.CharField(max_length=5)),
                ('amount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(choices=[('r01', 'Reason #1'), ('r02', 'Reason #2'), ('r03', 'Reason #3'), ('r04', 'Reason #4'), ('r05', 'Reason #5'), ('r06', 'Reason #6')], default='r01', max_length=5)),
                ('explanation', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('updated', models.DateTimeField(auto_now=True, help_text='timestamp of last update')),
            ],
        ),
        migrations.CreateModel(
            name='mcoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_liked', models.CharField(choices=[('mprod_exp180', 'Exp180'), ('mprod_intprep', 'Dialogue'), ('mprod_proflevel', 'Staircase'), ('mprod_proglang', 'Dialect'), ('mprod_rolebased', 'Identity'), ('mprod_strategy', 'Strategy'), ('mprod_visabased', 'Bandwidth'), ('mprod_xyz', 'General'), ('mprod_adhoc', 'Adhoc'), ('mprod_referral', 'Referral')], default='mprod_exp180', max_length=20)),
                ('discount_percent', models.IntegerField(default=1)),
                ('hours_to_expire', models.IntegerField(default=336)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
            ],
            options={
                'verbose_name_plural': 'Coupon Supported Product List',
            },
        ),
        migrations.CreateModel(
            name='mpaypal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_label', models.CharField(max_length=100)),
                ('response_data_json', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mprod_exp180',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=100)),
                ('saleprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('deliverables', models.TextField(blank=True, null=True)),
                ('serv_cat', models.CharField(choices=[('analysis', 'Analysis Service'), ('editing', 'Editing Service'), ('formatting', 'Formating Service')], default='analysis', max_length=200)),
                ('golivestatus', models.CharField(choices=[('active', 'Live'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('trending', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('homepage_showup', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20)),
                ('level', models.CharField(choices=[('adhoc_get_started', 'adhoc_get_started'), ('others', 'others')], default='others', max_length=20)),
            ],
            options={
                'verbose_name_plural': '01-Exp180-services',
            },
        ),
        migrations.CreateModel(
            name='mprod_exp180_catlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(choices=[('basic', 'basic'), ('advanced', 'advanced')], default='basic', max_length=30)),
            ],
            options={
                'verbose_name_plural': '01_exp180_Cat_List',
            },
        ),
        migrations.CreateModel(
            name='mprod_intprep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=100)),
                ('saleprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('deliverables', models.TextField(blank=True, null=True)),
                ('golivestatus', models.CharField(choices=[('active', 'Live'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('trending', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('homepage_showup', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20)),
            ],
            options={
                'verbose_name_plural': '03-Dialogue-services',
            },
        ),
        migrations.CreateModel(
            name='mprod_intprep_catlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(default='regular', max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': '03_Dialogue_Cat_List',
            },
        ),
        migrations.CreateModel(
            name='mprod_proflevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=100)),
                ('saleprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=100)),
                ('title', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField()),
                ('deliverables', models.TextField(blank=True, null=True)),
                ('golivestatus', models.CharField(choices=[('active', 'Live'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('trending', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('homepage_showup', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20)),
            ],
            options={
                'verbose_name_plural': '07-Staircase-services',
            },
        ),
        migrations.CreateModel(
            name='mprod_proflevel_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelname', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': '07_Staircase_Cat_List',
            },
        ),
        migrations.CreateModel(
            name='mprod_proglang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=100)),
                ('saleprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=100)),
                ('title', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField()),
                ('deliverables', models.TextField(blank=True, null=True)),
                ('golivestatus', models.CharField(choices=[('active', 'Live'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('trending', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('homepage_showup', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20)),
            ],
            options={
                'verbose_name_plural': '05-Dialect-services',
            },
        ),
        migrations.CreateModel(
            name='mprod_proglang_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langname', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': '05_Dialect_Cat_List',
            },
        ),
        migrations.CreateModel(
            name='mprod_rolebased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=100)),
                ('saleprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=100)),
                ('title', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField()),
                ('deliverables', models.TextField(blank=True, null=True)),
                ('golivestatus', models.CharField(choices=[('active', 'Live'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('trending', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('homepage_showup', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20)),
            ],
            options={
                'verbose_name_plural': '06-Identity-services',
            },
        ),
        migrations.CreateModel(
            name='mprod_rolebased_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolename', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': '06_Identity_Cat_List',
            },
        ),
        migrations.CreateModel(
            name='mprod_strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=100)),
                ('saleprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('deliverables', models.TextField(blank=True, null=True)),
                ('golivestatus', models.CharField(choices=[('active', 'Live'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('trending', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('homepage_showup', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20)),
            ],
            options={
                'verbose_name_plural': '09-Strategy-services',
            },
        ),
        migrations.CreateModel(
            name='mprod_strategy_taglist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(default='job search', max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': '09_Strategy_Cat_List',
            },
        ),
        migrations.CreateModel(
            name='mprod_visabased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=100)),
                ('saleprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=100)),
                ('title', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField()),
                ('deliverables', models.TextField(blank=True, null=True)),
                ('golivestatus', models.CharField(choices=[('active', 'Live'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('trending', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('homepage_showup', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20)),
            ],
            options={
                'verbose_name_plural': '08-Bandwidth-services',
            },
        ),
        migrations.CreateModel(
            name='mprod_visabased_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visaname', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': '08_Bandwidth_Cat_List',
            },
        ),
        migrations.CreateModel(
            name='msendmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=1000)),
                ('plain_message', models.TextField()),
                ('html_message', models.TextField()),
                ('from_email', models.CharField(default='', max_length=1000)),
                ('to_emails', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('updated', models.DateTimeField(auto_now=True, help_text='timestamp of last update')),
                ('sent_successfully', models.BooleanField(default=False)),
                ('appname', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='msku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threeletterprefix', models.CharField(max_length=3)),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'msku Services',
            },
        ),
        migrations.CreateModel(
            name='muniqueid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_uniqid', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('updated', models.DateTimeField(auto_now=True, help_text='timestamp of last update')),
                ('muser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='msendmail_failure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('recipient_string', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('updated', models.DateTimeField(auto_now=True, help_text='timestamp of last update')),
                ('msendmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeweb.msendmail')),
            ],
        ),
        migrations.CreateModel(
            name='mprod_visabased_serviceoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=2000)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeweb.mprod_visabased')),
            ],
            options={
                'verbose_name_plural': '08_Bandwidth_ServOption_Serv_List',
            },
        ),
        migrations.CreateModel(
            name='mprod_visabased_deliveryoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=2000)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('hours_to_cancel_after_payment', models.IntegerField(default=168)),
                ('hours_to_deliver_after_payment', models.IntegerField(default=336)),
                ('products', models.ManyToManyField(to='resumeweb.mprod_visabased')),
            ],
            options={
                'verbose_name_plural': '08_Bandwidth_DelivOption_List',
            },
        ),
        migrations.AddField(
            model_name='mprod_visabased',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeweb.mprod_visabased_list'),
        ),
        migrations.CreateModel(
            name='mprod_strategy_serviceoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=2000)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeweb.mprod_strategy')),
            ],
            options={
                'verbose_name_plural': '09_Strategy_ServOption_Serv_List',
            },
        ),
        migrations.CreateModel(
            name='mprod_strategy_deliveryoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=2000)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('hours_to_cancel_after_payment', models.IntegerField(default=168)),
                ('hours_to_deliver_after_payment', models.IntegerField(default=336)),
                ('products', models.ManyToManyField(to='resumeweb.mprod_strategy')),
            ],
            options={
                'verbose_name_plural': '09_Strategy_DelivOption_List',
            },
        ),
        migrations.AddField(
            model_name='mprod_strategy',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeweb.mprod_strategy_taglist'),
        ),
        migrations.CreateModel(
            name='mprod_rolebased_serviceoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=2000)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeweb.mprod_rolebased')),
            ],
            options={
                'verbose_name_plural': '06_Identity_ServOption_Serv_List',
            },
        ),
        migrations.CreateModel(
            name='mprod_rolebased_deliveryoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=2000)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('hours_to_cancel_after_payment', models.IntegerField(default=168)),
                ('hours_to_deliver_after_payment', models.IntegerField(default=336)),
                ('products', models.ManyToManyField(to='resumeweb.mprod_rolebased')),
            ],
            options={
                'verbose_name_plural': '06_Identity_DelivOption_List',
            },
        ),
        migrations.AddField(
            model_name='mprod_rolebased',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeweb.mprod_rolebased_list'),
        ),
        migrations.CreateModel(
            name='mprod_proglang_serviceoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=2000)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeweb.mprod_proglang')),
            ],
            options={
                'verbose_name_plural': '05_Dialect_ServOption_Serv_List',
            },
        ),
        migrations.CreateModel(
            name='mprod_proglang_deliveryoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=2000)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('hours_to_cancel_after_payment', models.IntegerField(default=168)),
                ('hours_to_deliver_after_payment', models.IntegerField(default=336)),
                ('products', models.ManyToManyField(to='resumeweb.mprod_proglang')),
            ],
            options={
                'verbose_name_plural': '05_Dialect_DelivOption_List',
            },
        ),
        migrations.AddField(
            model_name='mprod_proglang',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeweb.mprod_proglang_list'),
        ),
        migrations.CreateModel(
            name='mprod_proflevel_serviceoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=2000)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeweb.mprod_proflevel')),
            ],
            options={
                'verbose_name_plural': '07_Staircase_ServOption_Serv_List',
            },
        ),
        migrations.CreateModel(
            name='mprod_proflevel_deliveryoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=2000)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('hours_to_cancel_after_payment', models.IntegerField(default=168)),
                ('hours_to_deliver_after_payment', models.IntegerField(default=336)),
                ('products', models.ManyToManyField(to='resumeweb.mprod_proflevel')),
            ],
            options={
                'verbose_name_plural': '07_Staircase_DelivOption_List',
            },
        ),
        migrations.AddField(
            model_name='mprod_proflevel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeweb.mprod_proflevel_list'),
        ),
        migrations.CreateModel(
            name='mprod_intprep_serviceoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=2000)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeweb.mprod_intprep')),
            ],
            options={
                'verbose_name_plural': '03_Dialogue_ServOption_Serv_List',
            },
        ),
        migrations.CreateModel(
            name='mprod_intprep_deliveryoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=2000)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('hours_to_cancel_after_payment', models.IntegerField(default=168)),
                ('hours_to_deliver_after_payment', models.IntegerField(default=336)),
                ('products', models.ManyToManyField(to='resumeweb.mprod_intprep')),
            ],
            options={
                'verbose_name_plural': '03_Dialogue_DelivOption_List',
            },
        ),
        migrations.AddField(
            model_name='mprod_intprep',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resumeweb.mprod_intprep_catlist'),
        ),
        migrations.CreateModel(
            name='mprod_exp180_serviceoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=2000)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeweb.mprod_exp180')),
            ],
            options={
                'verbose_name_plural': '01_Exp180_ServOption_Serv_List',
            },
        ),
        migrations.CreateModel(
            name='mprod_exp180_deliveryoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=2000)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('hours_to_cancel_after_payment', models.IntegerField(default=168)),
                ('hours_to_deliver_after_payment', models.IntegerField(default=336)),
                ('products', models.ManyToManyField(to='resumeweb.mprod_exp180')),
            ],
            options={
                'verbose_name_plural': '01_Exp180_DelivOption_List',
            },
        ),
        migrations.AddField(
            model_name='mprod_exp180',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resumeweb.mprod_exp180_catlist'),
        ),
        migrations.CreateModel(
            name='mcoupon_given',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_string_32', models.CharField(max_length=33)),
                ('expired', models.BooleanField(default=False)),
                ('usedinpurchase', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('mcoupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeweb.mcoupon')),
            ],
            options={
                'verbose_name_plural': 'Coupon Code List',
            },
        ),
        migrations.CreateModel(
            name='mcart_serviceoptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Not Set', max_length=500)),
                ('sku', models.CharField(max_length=6)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='price', max_digits=1000)),
                ('serviceoption_id', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('updated', models.DateTimeField(auto_now=True, help_text='timestamp of last update')),
                ('mcart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeweb.mcart')),
            ],
        ),
        migrations.CreateModel(
            name='mcart_fileupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_uniqid', models.CharField(max_length=100)),
                ('purchased', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('updated', models.DateTimeField(auto_now=True, help_text='timestamp of last update')),
                ('document', models.FileField(upload_to=resumeweb.models.mcart_uploadpath())),
                ('validation_passed', models.BooleanField(default=False)),
                ('validation_failed_id', models.IntegerField(default=0)),
                ('mcompleted_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumeweb.mcompleted_purchase')),
            ],
        ),
        migrations.CreateModel(
            name='mcart_deliveryoptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Not Set', max_length=100)),
                ('sku', models.CharField(max_length=6)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='price', max_digits=1000)),
                ('hours_to_cancel_after_payment', models.IntegerField(default=168)),
                ('hours_to_deliver_after_payment', models.IntegerField(default=336)),
                ('deliveryoption_id', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('updated', models.DateTimeField(auto_now=True, help_text='timestamp of last update')),
                ('mcart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resumeweb.mcart')),
            ],
        ),
        migrations.CreateModel(
            name='mcart_coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('updated', models.DateTimeField(auto_now=True, help_text='timestamp of last update')),
                ('mcart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resumeweb.mcart')),
                ('mcoupon_given', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resumeweb.mcoupon_given')),
            ],
        ),
        migrations.AddField(
            model_name='mcart',
            name='mcompleted_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumeweb.mcompleted_purchase'),
        ),
        migrations.AddField(
            model_name='mcart',
            name='mcompleted_refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumeweb.mcompleted_refund'),
        ),
        migrations.AddField(
            model_name='mcart',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
